baseURL = "http://localhost:1313/"
title = "Home"
theme = "flewidfriendly"
disableKinds = ["taxonomy", "term"]
enableEmoji = true
math = false          # 
googleAnalytics = ""  # add your tracking id
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"

[params.enable]
 # Google Maps widget: If `googleMapsApiKey` is not set, no key will be passed to Google (which likely results in a broken map widget).
    enableGoogleMaps = true
    googleMapsApiKey = "AIzaSyAv7Sza8NSp9_l_g8G2vlo0H4ydEPn_2jY"

    latitude = "-12.043333"
    longitude = "-77.028333"
    



# - register your account to https://formspree.io/register
    # - login and create new form
    # - set your form's endpoint url under 'formspree_action' below
    # - upload the generated site to your server
    # - test a dummy email yourself
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io endpoint url
formspree_action = "https://formspree.io/sample/of/endpoint"
contact_form_ajax = true

    enableRecaptchaInContactForm = true
    googleRecaptchaKey = "site_key_for_google_recaptcha"

# - form actin key set here / Your form's endpoint is:
    formspreekey = "xvonddbb"



# number of words of summarized post content (default 70)
summaryLength = 70

# Define the number of posts per page
paginate = 10

[params]
mainSections = ['blogs']
lang = "en"
author = ""
description = "Better Blue Collar"
seoTitle = "Better Blue Collar"
favicon = "/img/favico.png"  # path to a .ico to use as favicon
logo = "/img/logo-original.png"  # url or path to a logo to put in the header
logo_black = "/img/logo-original.png"  # url or path to a logo to put in the header
formspree_action = "https://formspree.io/sample/of/endpoint"
contact_form_ajax = true

[params.footer]
text = "©2021 Better Blue Collar. All rights reserved"
url = "/"
description = ""


[params.footerContactus]
title = "Contact"
address1 = ""
address2 = ""
tel = "406-290-1437"
telNumber = "4062901437"
url = "mailto:contact@betterbluecollar.com"
text = "contact@betterbluecollar.com"


[[params.socialIcons]]
icon = "fab fa-facebook-f"
title = "facebook"
url = "https://www.facebook.com/boldthemes/"

[[params.socialIcons]]
icon = "fa-brands fa-twitter"
title = "twitter"
url = "https://twitter.com/bold_themes"

[[params.socialIcons]]
icon = "fab fa-instagram"
title = "instagram"
url = "https://www.instagram.com/bold_themes/?hl=en"

[[params.socialIcons]]
icon = "fa-brands fa-linkedin-in"
title = "linkedin"
url = "https://betterbluecollar.com/#"


[params.recent_posts]
enable = true
title = "Our Blog"
subtitle = "Find Our Latest Post"
hide_summary = false

# Format dates with Go's time formatting
date_format = "Mon, Jan 2, 2006"

[permalinks]
"/" = "/:filename"



# Main menu
[[menu.main]]
identifier = "menu.home"
name       = "Home"
url        = "/"
weight     = 1

[[menu.main]]
identifier = "menu.services"
name       = "Services"
url        = "/services"
weight     = 2

[[menu.main]]
identifier = "menu.about"
name       = "About"
url        = "/about"
weight     = 3


[[menu.footer1]]
identifier = "menu.home"
name       = "Home"
url        = "/"
weight     = 1

[[menu.footer1]]
identifier = "menu.services"
name       = "Services"
url        = "/services"
weight     = 2

[[menu.footer1]]
identifier = "menu.about"
name       = "About"
url        = "/about"
weight     = 3

[[menu.footer2]]
identifier = "menu.home"
name       = "Home"
url        = "/"
weight     = 1

[[menu.footer2]]
identifier = "menu.services"
name       = "Services"
url        = "/services"
weight     = 2

[[menu.footer2]]
identifier = "menu.about"
name       = "About"
url        = "/about"
weight     = 3

[params.hero]
enable = true
hero_text = "Progressive Investor Relations & Consulting"
hero_text_color = "#FFB600"
hero_text_dropshadow = true
hero_text_dropshadow_color = "#6AADF0"
hero_text_dropshadow_amount = "2px 7px 16px"
hero_button = true
hero_button_text = "About Us"
hero_button_color = "#6AADF0"
hero_button_bg_color = "#FFB600"
hero_button_link = "/about"

[[menu.herobar]]
weight = 1
name = "Phone"
url = "#"
pre = "Get Started"

[[menu.herobar]]
weight = 3
name = "Schedule a Demo"
url = "#"
pre = "Schedule a Demo"  

[[menu.herobar]]
weight = 4
name = "Contact Us"
url = "#contact"
pre = "Contact Us"

[params.packages]
enable = true
title = "Packages"
subtitle = "Get out of the business of being in the business."
cols = 3 # Default: 3, Available values 2,3,4,6

[params.blogs]
enable = true
title = "Smart Solutions for Small Business"
subtitle = "There is so much we can take off of your hands"
cols = 3 # Default: 3, Available values 2,3,4,6

[params.ourstory]
enable = true
title = "SAVING OUR PLANET ONE STRAW AT A TIME."
subtitle = "Single-use plastic straws may be small in size, but they are a BIG problem for the future of our planet.  These devilish little contraptions are so small and annoying that they end up everywhere, from our once-pristine beaches to our oceans, lakes, and waterways."
btntxt = "Read Our Story"
btnlink = "/about"

[params.howtouse]
enable = true
title = "How to Use" 

[params.contact]
enable = true
title = "Contact Us" 

[params.trustedpartners]
enable = true
title = "Trusted Partners" 
subtitle = "With our Company, you've got a friend in the tech business. We've built long-term relationships with trusted partners so you don't have to." 

[taxonomies]
category = "categories"
tag = "tags"
author = "authors"

# Enable and disable widgets for the right sidebar
[params.widgets]
categories = true
tags = true
search = true


[markup.goldmark.renderer]
unsafe = true  # allow raw HTML in markdown files
